In [72]:
import numpy as np
import pandas as pd

In [73]:
a = [2,3,4]
b=['a','b','c']
pd.Series(a,index=b)

a    2
b    3
c    4
dtype: int64

In [74]:
arr = {
    "one": [1,2,3],
    "two": [4,5,6],
    "three": [7,8,9]
}

In [75]:
pd.DataFrame(arr)

   one  two  three
0    1    4      7
1    2    5      8
2    3    6      9

In [76]:
arr2=[["Aryan","Sunil","Dahiya"],["Shlok","Navin","Shtty"]]
pd.DataFrame(arr2)

       0      1       2
0  Aryan  Sunil  Dahiya
1  Shlok  Navin   Shtty

In [77]:
NameFormat=["Name","Middle Name","Surnname"]
arr2=pd.DataFrame(arr2,columns=NameFormat)
arr2

    Name Middle Name Surnname
0  Aryan       Sunil   Dahiya
1  Shlok       Navin    Shtty

In [78]:
arr2.index=["a","b"]
arr2

    Name Middle Name Surnname
a  Aryan       Sunil   Dahiya
b  Shlok       Navin    Shtty

In [79]:
arr2["Name"]

a    Aryan
b    Shlok
Name: Name, dtype: object

In [80]:
arr2["J*B"]=["AIML Engineer","J*bless"]
arr2

    Name Middle Name Surnname            J*B
a  Aryan       Sunil   Dahiya  AIML Engineer
b  Shlok       Navin    Shtty        J*bless

In [81]:
arr2.drop("J*B",axis=1)

    Name Middle Name Surnname
a  Aryan       Sunil   Dahiya
b  Shlok       Navin    Shtty

In [82]:
arr2

    Name Middle Name Surnname            J*B
a  Aryan       Sunil   Dahiya  AIML Engineer
b  Shlok       Navin    Shtty        J*bless

In [83]:
arr2.drop("J*B",axis=1,inplace=True)
arr2

    Name Middle Name Surnname
a  Aryan       Sunil   Dahiya
b  Shlok       Navin    Shtty

In [84]:
arr2

    Name Middle Name Surnname
a  Aryan       Sunil   Dahiya
b  Shlok       Navin    Shtty

In [85]:
arr2.drop("b",axis=0)

    Name Middle Name Surnname
a  Aryan       Sunil   Dahiya

In [87]:
arr2

    Name Middle Name Surnname
a  Aryan       Sunil   Dahiya
b  Shlok       Navin    Shtty

In [89]:
arr2.loc["a"]

Name            Aryan
Middle Name     Sunil
Surnname       Dahiya
Name: a, dtype: object

In [91]:
arr2.loc[["a","b"]]

    Name Middle Name Surnname
a  Aryan       Sunil   Dahiya
b  Shlok       Navin    Shtty